Models/Hunting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FishingHunting.Models
{
    public class Hunting
    {
        public Guid ID { get; set; }
        public string HuntingProductName { get; set; }
        public string HuntingProductType { get; set; }
        public ICollection<Preferences> Preferences { get; set; }
    }
}

Controllers/HuntingController.cs
using FishingHunting.Models;
using FishingHunting.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace FishingHunting.Controllers
{
    
    public class HuntingController : Controller
    {
        private readonly HuntingService _huntingService;

        public HuntingController(HuntingService huntingService)
        {
            _huntingService = huntingService;
        }
        public IActionResult Index(string searchString)
        {
            var huntingitem = _huntingService.GetHuntingItem();
            if (!String.IsNullOrEmpty(searchString))
            {
                huntingitem = _huntingService.GetHuntingItemByCondition(s => s.HuntingProductType.Contains(searchString)
                                                                          || s.HuntingProductName.Contains(searchString));
            }
            return View(huntingitem);
        }

       
        // GET: Fishing/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var huntingitem = _huntingService.GetHuntingItem().FirstOrDefault(m => m.ID == id);
            if (huntingitem == null)
            {
                return NotFound();
            }

            return View(huntingitem);
        }

        // GET: Fishing/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fishing/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ID,HuntingProductName,HuntingProductType")] Hunting huntingitem)
        {
            if (ModelState.IsValid)
            {
                _huntingService.AddHuntingItem(huntingitem);
                _huntingService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(huntingitem);
        }

        // GET: Fishing/Edit/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var huntingitem = _huntingService.GetHuntingItem().FirstOrDefault(m => m.ID == id);
            if (huntingitem == null)
            {
                return NotFound();
            }
            return View(huntingitem);
        }

        // POST: Fishing/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("ID,HuntingProductName,HuntingProductType")] Hunting huntingitem)
        {
            if (id != huntingitem.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _huntingService.UpdateHuntingItem(huntingitem);
                    _huntingService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishingItemExists(huntingitem.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(huntingitem);
        }

        // GET: Fishing/Delete/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingItem = _huntingService.GetHuntingItem().FirstOrDefault(m => m.ID == id);
            if (fishingItem == null)
            {
                return NotFound();
            }

            return View(fishingItem);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var huntingitem = _huntingService.GetHuntingItemByCondition(b => b.ID == id).FirstOrDefault();
            _huntingService.DeleteHuntingItem(huntingitem);
            _huntingService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool FishingItemExists(Guid id)
        {
            return _huntingService.GetHuntingItem().Any(e => e.ID == id);
        }
        
    }
}

Views/Hunting/Create.cshtml
@model FishingHunting.Models.Hunting

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hunting Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HuntingProductName" class="control-label"></label>
                <input asp-for="HuntingProductName" class="form-control" />
                <span asp-validation-for="HuntingProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HuntingProductType" class="control-label"></label>
                <input asp-for="HuntingProductType" class="form-control" />
                <span asp-validation-for="HuntingProductType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Hunting/Delete.cshtml
@model FishingHunting.Models.Hunting

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hunting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HuntingProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HuntingProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HuntingProductType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HuntingProductType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Hunting/Details.cshtml
@model FishingHunting.Models.Hunting

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hunting Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HuntingProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HuntingProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HuntingProductType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HuntingProductType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Hunting/Edit.cshtml
@model FishingHunting.Models.Hunting

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Hunting Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="HuntingProductName" class="control-label"></label>
                <input asp-for="HuntingProductName" class="form-control" />
                <span asp-validation-for="HuntingProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HuntingProductType" class="control-label"></label>
                <input asp-for="HuntingProductType" class="form-control" />
                <span asp-validation-for="HuntingProductType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Hunting/Index.cshtml
@model IEnumerable<FishingHunting.Models.Hunting>

@{
    ViewData["Title"] = "Index";
}

<h1>Huting items list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Hunting" asp-action="Index" method="get">
    <p>
        Search by Type or Name:
        <input type="text" name="searchString" />
        <input type="submit" value="Search" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.HuntingProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HuntingProductType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.HuntingProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HuntingProductType)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>