Models/FishingPlace.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FishingHunting.Models
{
    public class FishingPlace
    {
        public Guid ID { get; set; }
        public string FishingPlaceName { get; set; }
        public string FishingLocation { get; set; }
        public ICollection<Preferences> Preferences { get; set; }
    }
}

Controllers/FishingController.cs
using FishingHunting.Models;
using FishingHunting.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FishingHunting.Controllers
{
    
    public class FishingController : Controller
    {
        private readonly FishingService _fishingService;

        public FishingController(FishingService fishingService)
        {
            _fishingService = fishingService;
        }
        [Authorize(Roles = "Administrator,User")]
        public IActionResult Index(string searchString)
        {
            var fishingItem = _fishingService.GetFishingItem();
            if (!String.IsNullOrEmpty(searchString))
            {
                fishingItem = _fishingService.GetFishingItemByCondition(s => s.FishingProductType.Contains(searchString) 
                                                                          || s.FishingProductName.Contains(searchString));
            }
            return View(fishingItem);
        }


        // GET: Fishing/Details/5
        
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingitem = _fishingService.GetFishingItem().FirstOrDefault(m => m.ID == id);
            if (fishingitem == null)
            {
                return NotFound();
            }

            return View(fishingitem);
        }

        // GET: Fishing/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fishing/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ID,FishingProductName,FishingProductType")] Fishing fishingItem)
        {
            if (ModelState.IsValid)
            {
                _fishingService.AddFishingItem(fishingItem);
                _fishingService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(fishingItem);
        }

        // GET: Fishing/Edit/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingitem = _fishingService.GetFishingItem().FirstOrDefault(m => m.ID == id);
            if (fishingitem == null)
            {
                return NotFound();
            }
            return View(fishingitem);
        }

        // POST: Fishing/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("ID,FishingProductName,FishingProductType")] Fishing fishingItem)
        {
            if (id != fishingItem.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _fishingService.UpdateFishingItem(fishingItem);
                    _fishingService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishingItemExists(fishingItem.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fishingItem);
        }

        // GET: Fishing/Delete/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingItem = _fishingService.GetFishingItem().FirstOrDefault(m => m.ID == id);
            if (fishingItem == null)
            {
                return NotFound();
            }

            return View(fishingItem);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var fishingitem = _fishingService.GetFishingItemByCondition(b => b.ID == id).FirstOrDefault();
            _fishingService.DeleteFishingItem(fishingitem);
            _fishingService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool FishingItemExists(Guid id)
        {
            return _fishingService.GetFishingItem().Any(e => e.ID == id);
        }
    }
}

Controllers/FishingPlaceController.cs
using FishingHunting.Models;
using FishingHunting.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FishingHunting.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class FishingPlaceController : Controller
    {
        private readonly FishingPlaceService _fishingPlaceService;

        public FishingPlaceController(FishingPlaceService fishingPlaceService)
        {
            _fishingPlaceService = fishingPlaceService;
        }
        [Authorize(Roles = "Administrator,User")]
        public IActionResult Index(string searchString)
        {
            var fishingPlace = _fishingPlaceService.GetFishingPlace();
            if (!String.IsNullOrEmpty(searchString))
            {
                fishingPlace = _fishingPlaceService.GetFishingPlaceByCondition(s => s.FishingLocation.Contains(searchString)
                                                                          || s.FishingPlaceName.Contains(searchString));
            }
            return View(fishingPlace);
        }


        // GET: Fishing/Details/5
       
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingPlace = _fishingPlaceService.GetFishingPlace().FirstOrDefault(m => m.ID == id);
            if (fishingPlace == null)
            {
                return NotFound();
            }

            return View(fishingPlace);
        }

        // GET: Fishing/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fishing/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ID,FishingPlaceName,FishingLocation")] FishingPlace fishingPlace)
        {
            if (ModelState.IsValid)
            {
                _fishingPlaceService.AddFishingPlace(fishingPlace);
                _fishingPlaceService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(fishingPlace);
        }

        // GET: Fishing/Edit/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingPlace = _fishingPlaceService.GetFishingPlace().FirstOrDefault(m => m.ID == id);
            if (fishingPlace == null)
            {
                return NotFound();
            }
            return View(fishingPlace);
        }

        // POST: Fishing/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("ID,FishingPlaceName,FishingLocation")] FishingPlace fishingPlace)
        {
            if (id != fishingPlace.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _fishingPlaceService.UpdateFishingPlace(fishingPlace);
                    _fishingPlaceService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishingPlaceExists(fishingPlace.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fishingPlace);
        }

        // GET: Fishing/Delete/5
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fishingPlace = _fishingPlaceService.GetFishingPlace().FirstOrDefault(m => m.ID == id);
            if (fishingPlace == null)
            {
                return NotFound();
            }

            return View(fishingPlace);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var fishingPlace = _fishingPlaceService.GetFishingPlaceByCondition(b => b.ID == id).FirstOrDefault();
            _fishingPlaceService.DeleteFishingPlace(fishingPlace);
            _fishingPlaceService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool FishingPlaceExists(Guid id)
        {
            return _fishingPlaceService.GetFishingPlace().Any(e => e.ID == id);
        }
    }
}

Views/FishingPlace/Create.cshtml
@model FishingHunting.Models.FishingPlace

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Fishing Places</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FishingPlaceName" class="control-label"></label>
                <input asp-for="FishingPlaceName" class="form-control" />
                <span asp-validation-for="FishingPlaceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FishingLocation" class="control-label"></label>
                <input asp-for="FishingLocation" class="form-control" />
                <span asp-validation-for="FishingLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FishingPlace/Delete.cshtml
@model FishingHunting.Models.FishingPlace

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fishing Item</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FishingPlaceName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FishingPlaceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FishingLocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FishingLocation)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/FishingPlace/Details.cshtml
@model FishingHunting.Models.FishingPlace

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Fishing Location</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FishingPlaceName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FishingPlaceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FishingLocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FishingLocation)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FishingPlace/Edit.cshtml
@model FishingHunting.Models.FishingPlace

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Fishing Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FishingPlaceName" class="control-label"></label>
                <input asp-for="FishingPlaceName" class="form-control" />
                <span asp-validation-for="FishingPlaceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FishingLocation" class="control-label"></label>
                <input asp-for="FishingLocation" class="form-control" />
                <span asp-validation-for="FishingLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FishingPlace/Index.cshtml
@model IEnumerable<FishingHunting.Models.FishingPlace>

@{
    ViewData["Title"] = "Index";
}

<h1>Fishing places list</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Fishing" asp-action="Index" method="get">
    <p>
        Search by Location or Name:
        <input type="text" name="searchString" />
        <input type="submit" value="Search" />
        
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.FishingPlaceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FishingLocation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
         
            <td>
                @Html.DisplayFor(modelItem => item.FishingPlaceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FishingLocation)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>